"""Generate the report's numbers from the locked artifacts.

Every statistic in the report is read from a locked result file, never typed by
hand. This script flattens those JSON artifacts into LaTeX definitions in
report/generated_numbers.tex; the text uses \\num{key} to print one. A key that
does not exist makes the report fail to compile, so a stale or missing value cannot
slip into the document. Each numeric value is written in several rounded forms:

    key        two decimals            key:1   one decimal
    key:3      three decimals          key:4   four decimals
    key:pct1   x100, one decimal       key:pct0  x100, no decimals
    key:int    rounded integer

Also writes report/generated_numbers.keys.txt (every key with its raw value) so the
author can find the key for a number.

Run:  python run_report_numbers.py
"""
from __future__ import annotations

import csv
import glob
import json
import os
import re

from src import config

ROOT = config.ROOT
REPORT = os.path.join(os.path.dirname(ROOT), "report")
R = os.path.join(ROOT, "results")
SOURCES = {
    "core.eval": "evaluation.json", "core.stats": "eval_stats.json", "core.wf": "walkforward.json",
    "core.placebo": "placebo_analysis.json", "core.faith": "faithfulness.json",
    "core.faithcmp": "faithfulness_comparison.json", "core.audit": "audit_eval.json",
    "core.cov": "sentiment_coverage.json", "core.regimes": "regimes.json",
    "core.costs": "cost_sweep.json", "core.recon": "reconciliation.json",
    "core.tests": "property_tests.json", "core.pilot": "user_study.json",
    "ext.eval": "extended/evaluation.json", "ext.stats": "extended/eval_stats.json",
    "ext.wf": "extended/walkforward.json", "ext.placebo": "extended/placebo_analysis.json",
    "ext.regimes": "extended/regimes.json", "ext.costs": "extended/cost_sweep.json",
    "ext.cov": "extended/sentiment_coverage.json", "ext.scal": "extended/shapley_scaling.json",
    "ext.universe": "../data/extended/universe.json",
    "inv": "run_inventory.json", "core.alloc": "allocation_summary.json", "core.faithful": "faithfulness_comparison.json", "lat": "latency.json", "ctr": "contrast.json",
    "arms": "user_study_arms.json", "pers": "persona_survey.json",
    "ext.recon": "extended/reconciliation.json",
}


def esc(s: str) -> str:
    return re.sub(r"([&%$#_{}])", r"\\\1", s).replace("~", r"\textasciitilde{}")


def variants(key: str, v):
    if isinstance(v, bool):
        yield key, "true" if v else "false"
    elif isinstance(v, int):
        yield key, f"{v:,}".replace(",", "{,}")
        yield key + ":int", str(v)
    elif isinstance(v, float):
        neg = lambda t: t.replace("-", r"\textminus{}")
        yield key, neg(f"{v:.2f}")
        for d in (1, 3, 4):
            yield f"{key}:{d}", neg(f"{v:.{d}f}")
        yield key + ":pct1", neg(f"{v * 100:.1f}")
        yield key + ":pct0", neg(f"{v * 100:.0f}")
        yield key + ":int", neg(f"{round(v):d}")
    elif isinstance(v, str):
        yield key, esc(v)


def walk(prefix: str, node, out: dict):
    if isinstance(node, dict):
        for k, v in node.items():
            walk(f"{prefix}.{re.sub(r'[^A-Za-z0-9_-]+', '-', str(k)).strip('-')}", v, out)
    elif isinstance(node, list):
        if len(node) <= 40:
            for i, v in enumerate(node):
                walk(f"{prefix}.{i}", v, out)
        out[f"{prefix}.len"] = len(node)
    elif node is not None:
        out[prefix] = node


def main() -> int:
    os.makedirs(REPORT, exist_ok=True)
    flat: dict = {}
    for prefix, rel in SOURCES.items():
        path = os.path.normpath(os.path.join(R, rel))
        if os.path.exists(path):
            walk(prefix, json.load(open(path)), flat)
    # derived: failed audit attempts and checks (each rejected sentence is tried twice)
    a = flat.get("core.audit.n_decisions")
    if a:
        first_fail = round((1 - flat["core.audit.pass_rate_first_try"]) * a)
        second_fail = round(flat["core.audit.template_fallback_rate"] * a)
        flat["core.audit.n_failed_attempts"] = first_fail + second_fail
        flat["core.audit.n_failed_checks"] = sum(v for k, v in flat.items()
                                                 if k.startswith("core.audit.failure_taxonomy."))
    # study rows from the two arm files, for the free-text quotations and counts
    for name, f in (("armA", "responses_main.csv"), ("armB", "responses_b.csv")):
        p = os.path.join(ROOT, "study", f)
        if os.path.exists(p):
            flat[f"{name}.n"] = len(list(csv.DictReader(open(p))))
    lines = ["% Generated by run_report_numbers.py from the locked artifacts. Do not edit.",
             r"\providecommand{\num}[1]{\ifcsname num:#1\endcsname\csname num:#1\endcsname\else\textbf{[[MISSING \detokenize{#1}]]}\fi}"]
    keys = []
    for key in sorted(flat):
        for k, s in variants(key, flat[key]):
            lines.append(r"\expandafter\gdef\csname num:" + k + r"\endcsname{" + s + "}")
        keys.append(f"{key}\t{flat[key]!r}")
    with open(os.path.join(REPORT, "generated_numbers.tex"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    with open(os.path.join(REPORT, "generated_numbers.keys.txt"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(keys) + "\n")
    print(f"{len(flat)} values from {sum(os.path.exists(os.path.normpath(os.path.join(R, r))) for r in SOURCES.values())} artifacts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
