"""Generate the report's results tables from the locked artifacts.

Writes report/generated_tables.tex: one \\newcommand per table body (the tabular
only), so no result cell in the report is typed by hand. The same numbers reach the
text through run_report_numbers.py. Verdicts on the objectives are computed here
from explicit criteria, so a verdict cannot disagree with the result beside it.

Run:  python run_report_tables.py
"""
from __future__ import annotations

import csv
import json
import os

import numpy as np

from src import config

ROOT = config.ROOT
R = os.path.join(ROOT, "results")
OUT = os.path.join(os.path.dirname(ROOT), "report", "generated_tables.tex")
MINUS = r"\textminus{}"


def J(rel):
    p = os.path.join(R, rel)
    return json.load(open(p)) if os.path.exists(p) else None


def f(x, d=2):
    return f"{x:.{d}f}".replace("-", MINUS)


def pct(x, d=1):
    return f(x * 100, d).replace(MINUS, MINUS) + r"\%"


def tab(colspec, header, rows):
    body = "\n".join(" & ".join(r) + r" \\" + "\n\\hline" for r in rows)
    return ("{\\small\\setlength{\\tabcolsep}{3pt}\n\\begin{tabular}{" + colspec + "}\n\\hline\n"
            + " & ".join(f"\\textbf{{{h}}}" for h in header) + " \\\\\n\\hline\n" + body + "\n\\end{tabular}}")


COLS = ["Total Return", "CAGR", "Ann. Volatility", "Sharpe", "Sortino", "Max Drawdown"]


def results_table(ev, sentiment=True):
    t = ev["main_table"]
    rows = []
    def add(label, key, sd=False):
        m = t[key]
        cells = []
        for c in COLS:
            v = m[c]
            if c in ("Sharpe", "Sortino"):
                s = f(v)
                if sd:
                    s += r" $\pm$ " + f(m["_sd"][c])
            else:
                s = pct(v)
                if sd:
                    s += r" $\pm$ " + f(m["_sd"][c] * 100, 1)
            cells.append(s)
        rows.append([label] + cells)
    keys = list(t)
    price_mean = next(k for k in keys if k.startswith("PPO (mean"))
    price_best = next(k for k in keys if k.startswith("PPO (best"))
    add("PPO price, mean of 5 seeds", price_mean, True)
    add("PPO price, best seed", price_best)
    if sentiment:
        sm = next((k for k in keys if k.startswith("PPO+sentiment (mean")), None)
        sb = next((k for k in keys if k.startswith("PPO+sentiment (best")), None)
        if sm:
            add("PPO+sentiment, mean of 5", sm, True)
            add("PPO+sentiment, best seed", sb)
    add("Buy and hold (1/N)", "Buy & Hold (1/N)")
    add("Markowitz (train-fit)", "Markowitz (train-fit)")
    add("12--1 momentum", "12-1 momentum")
    add("Random policy (mean of 100)", "Random policy (mean of 100)")
    add("Best asset (hindsight)", "Best asset (hindsight)")
    return tab("|p{3.6cm}|c|c|c|c|c|c|", ["Strategy", "Total ret.", "CAGR", "Vol.", "Sharpe", "Sortino", "Max DD"], rows)


def main() -> int:
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    out = ["% Generated by run_report_tables.py from the locked artifacts. Do not edit."]
    def define(name, body):
        out.append("\\newcommand{\\" + name + "}{" + body + "}")

    core, ext = J("evaluation.json"), J("extended/evaluation.json")
    define("tblCoreResults", results_table(core, True))
    if ext:
        define("tblExtResults", results_table(ext, False))

    # walk-forward, both universes
    wc, we = J("walkforward.json"), J("extended/walkforward.json")
    rows = []
    for i, w in enumerate(wc["windows"]):
        r = [w["window"].replace("->", r"$\to$").replace("-", "--", 0), str(w["test_days"]),
             f(w["agent_sharpe_mean"]) + r" $\pm$ " + f(w["agent_sharpe_std"]), f(w["buy_hold_sharpe"]),
             f"{w['n_beating_bh']}/5"]
        if we:
            x = we["windows"][i]
            r += [f(x["agent_sharpe_mean"]) + r" $\pm$ " + f(x["agent_sharpe_std"]), f(x["buy_hold_sharpe"]),
                  f"{x['n_beating_bh']}/5"]
        rows.append(r)
    define("tblWalk", tab("|l|c|c|c|c|c|c|c|", ["Train $\\to$ test", "Days", "Core Sharpe", "1/N", "Seeds $>$ 1/N",
                                                 "Extended Sharpe", "1/N", "Seeds $>$ 1/N"], rows))

    # regimes, both universes
    rc, re_ = J("regimes.json"), J("extended/regimes.json")
    rows = []
    for i, r in enumerate(rc["regimes"]):
        row = [r["regime"], str(r["days"]), f(r["agent_sharpe_mean"]) + r" $\pm$ " + f(r["agent_sharpe_sd"]),
               f(r["Buy & Hold (1/N)"]), f(r["12-1 momentum"]), f"{r['seeds_beating_1N']}/5"]
        if re_:
            x = re_["regimes"][i]
            row += [f(x["agent_sharpe_mean"]) + r" $\pm$ " + f(x["agent_sharpe_sd"]), f(x["Buy & Hold (1/N)"]),
                    f"{x['seeds_beating_1N']}/5"]
        rows.append(row)
    define("tblRegimes", tab("|l|c|c|c|c|c|c|c|c|", ["Regime", "Days", "Core agent", "1/N", "Momentum", "Beat",
                                                     "Ext. agent", "1/N", "Beat"], rows))

    # cost sweep
    cc, ce = J("cost_sweep.json"), J("extended/cost_sweep.json")
    rows = []
    for i, r in enumerate(cc["sweep"]):
        row = [f"{r['cost'] * 100:.2f}\\%", f(r["agent_sharpe_mean"]) + r" $\pm$ " + f(r["agent_sharpe_sd"]),
               f"{r['seeds_beating_1N']}/5", pct(r["mean_daily_turnover"])]
        if ce:
            x = ce["sweep"][i]
            row += [f(x["agent_sharpe_mean"]) + r" $\pm$ " + f(x["agent_sharpe_sd"]), f"{x['seeds_beating_1N']}/5",
                    pct(x["mean_daily_turnover"])]
        rows.append(row)
    define("tblCosts", tab("|c|c|c|c|c|c|c|", ["Cost", "Core Sharpe", "Beat 1/N", "Turnover", "Ext. Sharpe",
                                               "Beat 1/N", "Turnover"], rows))

    # Shapley scaling
    sc = J("extended/shapley_scaling.json")
    if sc:
        rows = [[r["universe"], str(r["inputs"]), f"{r['n_perm']:,}".replace(",", "{,}"),
                 f(r["closed_form_max_abs_err"], 4)] for r in sc["scaling"] if "n_perm" in r]
        define("tblScaling", tab("|l|c|c|c|", ["Universe", "Inputs", "Permutations", "Max abs. error"], rows))

    # run inventory
    inv = J("run_inventory.json")
    rows = []
    for r in inv["runs"]:
        rows.append([r["universe"], r["variant"].replace("&", r"\&"), str(r["runs"]), r["window"].replace("->", r"$\to$"),
                     r["role"], "yes" if r["counts_toward_trials"] else "no"])
    define("tblInventory", tab("|l|l|c|p{3.2cm}|l|c|", ["Universe", "Variant", "Runs", "Window", "Role", "In trials"], rows))

    # property tests
    pt = J("property_tests.json")
    rows = [[str(i + 1), t["property"].split(". ", 1)[-1].replace("<", "$<$").replace("×", "$\\times$").replace("%", "\\%"), t["result"]]
            for i, t in enumerate(pt["tests"])]
    define("tblTests", tab("|c|l|c|", ["\\#", "Property", "Result"], rows))

    # user-study arms
    arms = J("user_study_arms.json")
    A = list(csv.DictReader(open(os.path.join(ROOT, "study", "responses_main.csv"))))
    B = list(csv.DictReader(open(os.path.join(ROOT, "study", "responses_b.csv"))))
    def cnt(rows_, t, state):
        return sum(json.loads(r["task_status"])[t] == state for r in rows_)
    def ci(d):
        return f"{f(d['diff_B_minus_A'])} [{f(d['ci95'][0])}, {f(d['ci95'][1])}]"
    rows = [["SUS score (0--100)", f(arms["sus"]["mean_A"], 1) + r" $\pm$ " + f(arms["sus"]["sd_A"], 1),
             f(arms["sus"]["mean_B"], 1) + r" $\pm$ " + f(arms["sus"]["sd_B"], 1), ci(arms["sus"]), f(arms["sus"]["perm_p"], 3)],
            ["Trust change (1--5)", f(arms["trust_change"]["mean_A"]) + r" $\pm$ " + f(arms["trust_change"]["sd_A"]),
             f(arms["trust_change"]["mean_B"]) + r" $\pm$ " + f(arms["trust_change"]["sd_B"]), ci(arms["trust_change"]),
             f(arms["trust_change"]["perm_p"], 3)],
            ["Trust after use (1--5)", f(arms["trust_post"]["mean_A"]) + r" $\pm$ " + f(arms["trust_post"]["sd_A"]),
             f(arms["trust_post"]["mean_B"]) + r" $\pm$ " + f(arms["trust_post"]["sd_B"]), ci(arms["trust_post"]),
             f(arms["trust_post"]["perm_p"], 3)],
            ["Tasks done unaided (share)", f(arms["unaided_share"]["mean_A"]), f(arms["unaided_share"]["mean_B"]),
             ci(arms["unaided_share"]), f(arms["unaided_share"]["perm_p"], 3)]]
    for t, name in enumerate(["Task 1, create a portfolio", "Task 2, read the recommendation", "Task 3, find the reason"]):
        rows.append([name + ": unaided / partial / failed",
                     f"{cnt(A, t, 'unaided')} / {cnt(A, t, 'partial')} / {cnt(A, t, 'failed')}",
                     f"{cnt(B, t, 'unaided')} / {cnt(B, t, 'partial')} / {cnt(B, t, 'failed')}", "", ""])
    define("tblArms", tab("|p{4.4cm}|c|c|c|c|", ["Measure", "Build A (n=10)", "Build B (n=10)",
                                                  "B $-$ A [95\\% CI]", "Perm. $p$"], rows))

    # objectives: verdicts computed from explicit criteria
    st, wf = J("eval_stats.json"), J("faithfulness_comparison.json")
    au = J("audit_eval.json")
    pooled = st["pooled_vs_1N"]
    o1 = not (pooled["ci_low"] > 0 and core["main_table"][next(k for k in core["main_table"] if k.startswith("PPO (mean"))]["Sharpe"]
              > core["main_table"]["Buy & Hold (1/N)"]["Sharpe"])
    o2 = wf["shapley_area_ci95"][0] > 0
    task1_b = cnt(B, 0, "unaided") / len(B)
    sus_b = arms["sus"]["mean_B"]
    o3 = "met" if (task1_b >= 0.5 and sus_b >= 68) else ("partly met" if (task1_b >= 0.5 or sus_b >= 68) else "not met")
    o4 = arms["trust_change"]["ci95"][1] < 0
    ppo = core["main_table"][next(k for k in core["main_table"] if k.startswith("PPO (mean"))]["Sharpe"]
    rows = [
        ["O1 risk-adjusted return above 1/N", "five-seed mean Sharpe; pooled bootstrap vs 1/N",
         f"mean {f(ppo)} against {f(core['main_table']['Buy & Hold (1/N)']['Sharpe'])}; difference {f(pooled['sharpe_diff'])} "
         f"[{f(pooled['ci_low'])}, {f(pooled['ci_high'])}]", "not met" if o1 else "met"],
        ["O2 faithful, audited explanations", "deletion area with bootstrap interval; audit",
         f"area {f(wf['shapley_area_mean'], 3)} [{f(wf['shapley_area_ci95'][0], 3)}, {f(wf['shapley_area_ci95'][1], 3)}]; "
         f"every shown sentence passes ({pct(au['pass_rate'], 0)} on the model's own output)", "met" if o2 else "not met"],
        ["O3 independent use by a non-expert", "task 1 unaided share; SUS",
         f"task 1 unaided {cnt(B, 0, 'unaided')}/{len(B)} (build B); SUS {f(sus_b, 1)} against the benchmark 68", o3],
        ["O4 explanations raise trust", "trust change, build A against build B",
         f"B $-$ A {f(arms['trust_change']['diff_B_minus_A'])} [{f(arms['trust_change']['ci95'][0])}, "
         f"{f(arms['trust_change']['ci95'][1])}]", "met in direction" if o4 else "not met"],
    ]
    define("tblObjectives", tab("|p{3.0cm}|p{2.8cm}|p{5.2cm}|p{1.6cm}|", ["Objective", "Instrument", "Result", "Verdict"], rows))
    for i, k in enumerate(["o1", "o2", "o3", "o4"]):
        define("verdict" + k.upper()[0] + "abcd"[i] if False else "verdict" + "ABCD"[i], rows[i][3])

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    print("tables written:", len(out) - 1)
    print([r[3] for r in rows])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
